export const MessageConstants = {
    SUBSCRIBE_SUCCESS: "Thank you for Subscribing",
    SUBSCRIBE_ERROR: "Please Enter a Valid Email",
    CART_SUCCESS: "Product has been added in Cartlist.",
    WISHLIST_SUCCESS: "Product has been added in Wishlist.",
    ADDREVIEW_SUCCESS: "Thank you for Submit your Review.",
    ADDREVIEW_ERROR: "Please Fill Both StarRating & Review.",
    LOGIN_SUCCESS: " Login Successfully",
    LOGIN_ERROR: " Please Enter a Valid username and password",
    LOGIN_API_ERROR: " Something Went Wrong",
    NEWUSER_OTP_VERFIY: "OTP SEND YOUR MobileNumber",
    REGISTER_SUCCESS: "Registered Successfully",
    REGISTER_ERROR: "Invaild Otp",
    FORGOTPASSWORD_SUCCESS: "Password changed successfully",
    FORGOTPASSWORD_ERROR: "Invaild Otp",
    USER_EXISTS: "User Already Exists",
    USER_NOT_FOUND: "No User Found",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
    INVALID_DATA:"Invaild Otp",
    REQUESTCHANGENUMBER_ERROR:"Enter a Valid MobileNumber",
    CHANGENUMBER_ERROR:"Invaild Otp"
};
